# Generated by Django 5.0.6 on 2024-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0003_auto_20201013_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_det',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='d_profile',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='p_det',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
